site_name: Road to Verification
site_description: Personal blog of a Digital IC Verification Engineer.
site_url: https://choya-lee.github.io/verifi_blog/
site_author: zyli

copyright: Copyright &copy; 2025 -  zyli

theme:
  name: material
  logo: avatar.png
  favicon: avatar.png
  custom_dir: overrides

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow

  font:
    text: Roboto
    code: Roboto Mono

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - blog:
      blog_dir: .
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      categories_allowed:
        - PCIE
        - UVM
        - CXL
      post_url_format: "{slug}"

  - tags:
      enabled: true
      tags: true

  - rss:
      match_path: "posts/.*"
      pretty_print: true
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  
  - git-committers:
      enabled: true
      repository: choya-lee/verifi_blog
      branch: main
      token: !ENV GH_TOKEN
  
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: false
      enable_creation_date: true
      enable_git_follow: false
      enabled: true

# extra:
#   social:
#   - icon: /fontawesome/regular/envelope
#     name: send me an email
#     link: mailto:<fake@qq.com> 

# hooks:
  # - hooks/socialmedia.py

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# page tree
nav:
- Home: index.md
- Protocol: posts/protocol/pcie/physical_layer.md